[platformio]
default_envs = esp32dev, esp32-s3-devkitm, uno

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:esp32-s3-devkitm]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
